#!/usr/bin/env node
/*
 * Pre-processor for the bundled SVG icon set (`assets/icons/`).
 *
 * Scans every `*.svg` under assets/icons and emits a typed name→path map to
 * `src/icons.generated.ts`, e.g. `cat-sleeping-symbolic.svg` becomes
 * `CAT_SLEEPING: 'assets/icons/cat-sleeping-symbolic.svg'`. The `-symbolic` suffix
 * is dropped from the key (the path keeps it — GTK recolors an icon to the theme
 * foreground only when its filename ends in `-symbolic.svg`; see src/icons.ts).
 * The loader in `src/icons.ts` turns that map into the `ImageIcons` builders the
 * app uses, so adding an icon is just dropping an SVG in the folder and re-running
 * this script (wired into `postinstall`; also `pnpm run generate-icons`).
 *
 *   node scripts/generate-icons.ts
 */
import * as Fs from 'node:fs';
import * as Path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT_DIR = Path.join(Path.dirname(fileURLToPath(import.meta.url)), '..');
const ICONS_DIR = Path.join(ROOT_DIR, 'assets', 'icons');
const OUTPUT_FILE = Path.join(ROOT_DIR, 'src', 'icons.generated.ts');

// `cat-sleeping-symbolic.svg` → `CAT_SLEEPING`: drop the `-symbolic` marker (it's a
// rendering hint, not part of the name), then build a constant-style identifier
// (anything non-alphanumeric collapses to a single underscore).
function toConstName(filename: string): string {
  return Path.basename(filename, '.svg')
    .replace(/-symbolic$/, '')
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

const icons = Fs.readdirSync(ICONS_DIR)
  .filter((name) => name.endsWith('.svg'))
  .sort()
  .map((name) => ({ key: toConstName(name), path: `assets/icons/${name}` }));

if (icons.length === 0) throw new Error(`No SVG icons found in ${ICONS_DIR}`);

const duplicates = icons.filter((icon, i) => icons.findIndex((o) => o.key === icon.key) !== i);
if (duplicates.length > 0) {
  throw new Error(`Icon name collision after normalization: ${duplicates.map((d) => d.key).join(', ')}`);
}

const entries = icons.map(({ key, path }) => `  ${key}: '${path}',`).join('\n');
const contents = `// AUTO-GENERATED by scripts/generate-icons.ts — do not edit by hand.
// Run \`pnpm run generate-icons\` after adding or renaming an SVG in assets/icons/.
// Paths are repo-root-relative; the loader in src/icons.ts resolves them.

export const ICON_FILES = {
${entries}
} as const;
`;

Fs.writeFileSync(OUTPUT_FILE, contents);
console.log(`generate-icons: wrote ${icons.length} icon(s) to ${Path.relative(ROOT_DIR, OUTPUT_FILE)}`);
