// AUTO-GENERATED by scripts/generate-icons.ts — do not edit by hand.
// Run `pnpm run generate-icons` after adding or renaming an SVG in assets/icons/.
// Paths are repo-root-relative; the loader in src/icons.ts resolves them.

export const ICON_FILES = {
  BIG_DOT: 'assets/icons/big-dot-symbolic.svg',
  CAT_SLEEPING: 'assets/icons/cat-sleeping-symbolic.svg',
  CIRCLE_OUTLINE: 'assets/icons/circle-outline-symbolic.svg',
  DOT: 'assets/icons/dot-symbolic.svg',
  LOADING: 'assets/icons/loading-symbolic.svg',
  MEDIA_PLAYBACK_STOP: 'assets/icons/media-playback-stop-symbolic.svg',
  WARNING: 'assets/icons/warning-symbolic.svg',
} as const;
